spring:
  profiles:
    #启用application-dev配置文件
    active: dev
  freemarker:
    ##设置freemarker的路径
    template-loader-path: classpath:/page
    ##设置文件的后缀
    suffix: .html
    content-type: text/html;charset=UTF-8
    request-context-attribute: request
  ##设置静态文件路径
  mvc:
    static-path-pattern: /static/**